site = "https://chats-share.yelo.ooo"
public_dir = "public"
out_dir = "dist"

[template.options]
title = "chats-share"
subtitle = "the conversations bewteen me and my ai agent"
description = "OpenClaw Chats Share - A place for sharing and exploring AI chat conversations."
footer = "powered by [@imyelo](https://github.com/imyelo) &times; [@lambda610](https://github.com/lambda610)"
